config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :title, presence: true
    validates :contents, length: {maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start, :end, :allday, :contents))
      
    #終日のチェック判断
    if @schedule.allday == "true"
      @result = "○"
    else
      @result = ""
    end
      
    if @schedule.start > @schedule.end
      flash[:notice] = "終了日時は開始日時より後に設定してください。"
      render "new"
    elsif @schedule.save
      flash[:notice] = "スケジュールを追加しました。"
      redirect_to :schedules
    else
      flash[:notice] = "スケジュール登録に失敗しました。"
      render "new"
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])

    #終日のチェック判断
    if @schedule.allday == "true"
      @result = "○"
    else
      @result = ""
    end

    if @schedule.start > @schedule.end
      flash[:notice] = "終了日時は開始日時より後に設定してください。"
      render "edit"
    elsif @schedule.update(params.require(:schedule).permit(:title, :start, :end, :allday, :contents))
      flash[:notice] = "#{@schedule.title} の情報を更新しました。"
      redirect_to :schedules
    else
      flash[:notice] = "更新に失敗しました。"
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    flash[:notice] = "スケジュール：#{@schedule.title} を削除しました。"
    @schedule.destroy
    redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュールアプリ</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h3>スケジュール編集</h3>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |sc| %>
    <table>
        <tr>
            <th><%= sc.label :title,"タイトル" %></th>
            <td><%= sc.text_field :title %></td>
        </tr>
        <tr>
            <th><%= sc.label :start,"開始日時" %></th>
            <td><%= sc.datetime_select :start %></td>
        </tr>
        <tr>
            <th><%= sc.label :end,"終了日時" %></th>
            <td><%= sc.datetime_select :end %></td>
        </tr>
        <tr>
            <th><%= sc.label :allday,"終日" %></th>
            <td>
                <%= sc.check_box :allday,{style: 'transform: scale(1.5);'}, "○", " " %>
            </td>
        </tr>
        <tr>
            <th>
                <%= sc.label :contents,"内容" %>
                <p class="caution">  ※最大100文字まで</p>
            </th>
            <td>
                <%= sc.text_area :contents, size:"40%" %></tr>
            </td>
    </table>

    <div>
        <ul>
            <li><%= sc.submit "編集を完了する" %></li>
            <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
        </ul>
    </div>
<% end %>

app/views/schedules/index.html.erb
<h3>スケジュール一覧</h3>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
    <thead>
        <tr>
            <th class="wid1">id</th>
            <th class="wid4">タイトル</th>
            <th class="wid3">開始</th>
            <th class="wid3">終了</th>
            <th class="wid1">終日</th>
            <th class="wid3">更新日</th>
            <th class="wid2">確認</th>
            <th class="wid2">編集</th>
            <th class="wid2">削除</th>
        </tr>
    </thead>

    <tbody>
        <% @schedules.each do |sc| %>
            <tr>
                <td>
                    <%= sc.id %> 
                </td>
                <td><%= link_to sc.title, schedule_path(sc.id) %></td>
                <td><%= sc.start.to_s(:datetime_jp) %></td>
                <td><%= sc.end.to_s(:datetime_jp) %></td>
                <td><%= sc.allday %></td>
                <td><%= sc.updated_at.to_s(:date_jp) %></td>
                <td>
                    <%= link_to "確認", schedule_path(sc.id) %>
                </td>
                <td>
                    <%= link_to "編集", edit_schedule_path(sc.id) %>
                </td>
                <td>
                    <%= link_to "削除", schedule_path(sc.id), method: :delete, data: { confirm:"削除しますか？" } %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<p class="new"><%= link_to "スケジュール新規登録", :new_schedule %></p>

app/views/schedules/new.html.erb
<h3>スケジュール登録</h3>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |sc| %>
    <table>
        <tr>
            <th><%= sc.label :title,"タイトル" %></th>
            <td><%= sc.text_field :title %></td>
        </tr>
        <tr>
            <th><%= sc.label :start,"開始日時" %></th>
            <td><%= sc.datetime_select :start %></td>
        </tr>
        <tr>
            <th><%= sc.label :end,"終了日時" %></th>
            <td><%= sc.datetime_select :end %></td>
        </tr>
        <tr>
            <th><%= sc.label :allday,"終日" %></th>
            <td>
                <%= sc.check_box :allday,{style: 'transform: scale(1.5);'}, "○", " " %>
            </td>
        </tr>
        <tr>
            <th>
                <%= sc.label :contents,"内容" %> 
                <p class="caution">  ※最大100文字まで</p>
            </th>
            <td>
                <%= sc.text_area :contents, size:"40%" %>
            </td>
        </tr>
    </table>

    <div>
        <ul>
            <li class="submit"><%= sc.submit "登録" %></li>
            <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
        </ul>
    </div>
<% end %>

app/views/schedules/show.html.erb
<h3> <%= @schedule.title %> のスケジュール詳細</h3>

<table>
    <tr>
        <th class="wid3">名前</th>
        <td><%= @schedule.title %></td>
    </tr>
    <tr>
        <th class="wid3">開始</th>
        <td><%= @schedule.start.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
        <th class="wid3">終了</th>
        <td><%= @schedule.end.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
        <th class="wid3">終日</th>
        <td><%= @result %></td>
    </tr>
    <tr>
        <th class="wid3">内容</th>
        <td><%= @schedule.contents %></td>
    </tr>
</table>

<div>
    <p>前回更新日:<%= @schedule.updated_at.to_s(:date_jp) %></p>
</div>

<div>
    <%= link_to edit_schedule_path(@schedule.id) do %>
        <span class="button">編集</span>
    <% end %>
    <span>　</span>
    <%= link_to schedule_path(@schedule.id), method: :delete,data: {confirm:"削除しますか？"} do %>
        <span class="button">削除</span>
    <% end %>
</div>

<div>
    <ul>
        <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></li>
        </ul>
    <% end %>
<% end %>